name: CaseOpening
version: '${project.version}'
main: de.robble.caseopening.Main
api-version: 1.18

commands:
  kisten:
    description: lässt dich kisten öffnen und kaufen
  dkspin:
  ekspin:
  vkspin: